### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Rombur** [iSchomer/DualFoil_Data#8]
- [x] don't use `shell=True`
- [x] don't use `make` in `__init__`
- [x] don't use `date` use `datetime`
- [x] use one function to set the path and call it every where
- [x] `path` default should be `None`
- [x] `get_total_time` in seconds and only one implementation
- [x] variable name: name of the variables need to make more sense, need to document the variables better, use only one rule to name the variables
- [x] don't use `+=` to append on a list. Look at `extend`
- [x] what happens when the path is wrong
- [x] in test explain why the tolerance is relaxed for the potential
- [x] improve test using different time steps
- [x] explain how to install/use the code

**Comment by dalg24** [comment]
```
from datetime import datetime
datetime.now().isoformat() # will return a string representing the date and time in ISO 8601 format, YYYY-MM-DDTHH:MM:SS.mmmmmm
```
